#!/usr/bin/env bash
#Proclaiming variables, adding them to our text using the echo command and using variables
while IFS= read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_D CMDSHELL
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_D and rides $CMDSHELL. $USER_ID place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < /etc/passwd
