#!/usr/bin/env bash
#Proclaiming variables, adding them to our text using the echo command and using variables
while IFS= read -r;
USERNAME=$(cut -d ':' -f 1)
GROUP_ID=$(cut -d ':' -f 4)
HOME_D=$(cut -d ':' -f 6)
CMDSHELL=$(cut -d ':' -f 7)
USER_ID=$(cut -d ':' -f 3)
PASSWORD=$(cut -d ':' -f 2)
USER_ID_INFO=$(cut -d ':' -f 5)
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_D and rides $CMDSHELL. $USER_ID place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < /etc/passwd
