#!/usr/bin/env bash
#variable is 1, while x is less/equal 20 print variable, keep adding to variable each loop, if x touch 5, 10, 18 then print text that is listed
x=1
while [ $x -le 20 ]
do
	echo "$x"
	((x++))
case $x in
	5)
		echo "bad luck from China"
		;;
	10)
		echo "bad luck from Japan"
		;;
	18)
		echo "bad luck from Italy"
esac
done
