#!/usr/bin/env bash
#for variable holds the command ls, now we echo the variable (command) then we cut off the - in feild 2
directorylist=$(ls)
for i in $directorylist
do
	echo "$i" | cut -d '-' -f 2
done
