#!/usr/bin/env bash
#if the school files exists then print that it does, unless it doesnt then exit the loop, if it does then continue to checking if its empty then check if its a regular file
if [ -e "school" ]; then
	echo 'school file exists'
else 
	echo 'school file does not exist'
	exit 1
fi
if [ ! -s "school" ]; then
       echo 'school file is empty'
else
	echo 'school file is not empty'
fi
if
	[ -f "school" ]; then
	echo 'school file is a regular file'
fi
