#!/usr/bin/env bash
#trapping SIGTERM, SIGINT, SIGQUIT while displaying messages.
echo "pgrep /var/run/myscript.pid" > /var/run/myscript.pid
trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me?!"' 2
trap "rm /var/run/myscript.pid" 3 15
while true; do
	echo To infinity and beyond
	sleep 2
done
