#!/usr/bin/env bash
#
touch /var/run/myscript.pid | echo "pgrep /var/run/myscript.pid"
trap "echo I hate the killcommand" 15
trap "echo Y U no love me?!"
trap "rm /var/run/myscript.pid" 3 15
while true; do
	echo To infinity and beyond
	sleep 1
done
