#!/usr/bin/env bash
#
eric=$1
start() {
	./manage_my_process &
	echo "$!" > "/var/run/my_process.pid"
}

stop() {
	sudo pkill -f "./manage_my_process" && sudo rm "/var/run/my_process.pid"
}

restart() {
	stop && start
}

case "$eric" in
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		restart
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
