#!/usr/bin/env bash
#
case $1 in
	start)
		./manage_my_process &
		echo "pgrep /var/run/my_process.pid" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		sudo pkill -15 -f "manage_my_process"
		rm "/var/run/my_process.pid"
		echo "manage_my_process stopped"
		;;
	restart)
		sudo pkill -15 -f "manage_my_process"
                rm "/var/run/my_process.pid"
		./manage_my_process &
		echo "pgrep /var/run/my_process.pid" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
