#!/usr/bin/env bash
#
hi="$1"
case $hi in
	start)
		./manage_my_process &
		echo "$!" > "/var/run/my_process.pid"
		echo "manage_my_process started"
		;;
	stop)
		echo "manage_my_process stopped"
		sudo pkill -f "manage_my_process"
		rm "/var/run/my_process.pid"
		;;
	restart)
		echo "manage_my_process restarted"
		sudo pkill -f "manage_my_process"
                rm "/var/run/my_process.pid"
		./manage_my_process &
		echo "$!" > "/var/run/my_process.pid"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
